version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/srv/db-data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
