apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: default
spec:
  taskRef:
    name: create-webhook
  params:
    - name: GitHubOrg
      value: "eas-kaine"
    - name: GitHubUser
      value: "eas-kaine"
    - name: GitHubRepo
      value: "discord-bot"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: tekton.easlab.co.uk
  #   If you are using github enterprise, provide a value for GitHubDomain
  #  - name: GitHubDomain
  #    value: git.corp.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
